# Generated by Django 3.2.6 on 2021-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_pr_li'),
    ]

    operations = [
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=100)),
                ('e', models.EmailField(max_length=254)),
                ('com', models.CharField(max_length=100)),
            ],
        ),
    ]
